CREATE TABLE Dance (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DanceName TEXT NOT NULL,
	Video TEXT,
	Source TEXT
);

CREATE TABLE Steps (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DanceID INTEGER,
	StepName TEXT,
	FOREIGN KEY (ID) REFERENCES FigureStep (StepId)
	FOREIGN KEY (DanceID) REFERENCES Dance (ID)
);

CREATE TABLE User (
	ID INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	Email TEXT NOT NULL,
	State TEXT,
	City TEXT
);

CREATE TABLE Figure (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Roles TEXT NOT NULL,
	StartPosition TEXT NOT NULL,
	Action TEXT NOT NULL,
	EndPosition TEXT NOT NULL,
	Duration INTEGER NOT NULL,
	FOREIGN KEY (ID) REFERENCES FigureStep (FigureId)
);

CREATE TABLE Learning (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	UserId TEXT,
	DanceId TEXT,
	DateAdded TEXT,
	FOREIGN KEY (UserId) REFERENCES User (ID),
	FOREIGN KEY (DanceId) REFERENCES Dance (ID)
);

CREATE TABLE Favorites (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	UserId TEXT,
	DanceId TEXT,
	DateAdded TEXT,
	Rating INTEGER,
	FOREIGN KEY (UserId) REFERENCES User (ID),
	FOREIGN KEY (DanceId) REFERENCES Dance (ID)
);

CREATE TABLE FigureStep (
	StepsId INTEGER,
	FigureId INTEGER,
	Place INTEGER,
	PRIMARY KEY (StepsId, FigureId),
);
