-- this is the schema for the dances
CREATE TABLE Dance (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DanceName TEXT NOT NULL,
	Vlink TEXT,
	Date TEXT,
	Source TEXT,
	StepsId INTEGER NOT NULL,
	FOREIGN KEY (StepsId) REFERENCES Steps (ID)
);

CREATE TABLE Steps (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	StepName TEXT,
	Sequence TEXT,
	FOREIGN KEY (ID) REFERENCES FigureStep (StepId)
);

CREATE TABLE User (
	ID INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	Email TEXT NOT NULL,
	State TEXT,
	City TEXT
);

CREATE TABLE Figure (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Move TEXT NOT NULL,
	FOREIGN KEY (ID) REFERENCES FigureStep (FigureId)
);

CREATE TABLE Learning (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	UserId TEXT,
	DanceId TEXT,
	DateAdded TEXT,
	FOREIGN KEY (UserId) REFERENCES User (ID),
	FOREIGN KEY (DanceId) REFERENCES Dance (ID)
);

CREATE TABLE Favorites (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	UserId TEXT,
	DanceId TEXT,
	DateAdded TEXT,
	Rating INTEGER,
	FOREIGN KEY (UserId) REFERENCES User (ID),
	FOREIGN KEY (DanceId) REFERENCES Dance (ID)
);

CREATE TABLE FigureStep (
	StepsId INTEGER,
	FigureId INTEGER,
	Place INTEGER,
	PRIMARY KEY (StepId, FigureId),
);
